services:
  web:
    build: .
    image: swarmagentic-web:latest
    ports:
      - "8000:8000"
    environment:
      - HF_HOME=/cache/huggingface
      - BERT_MODEL_ID=prajjwal1/bert-tiny
    volumes:
      - ./:/app
      - ./.cache/huggingface:/cache/huggingface
      - ./results:/app/results
      - ./logs:/app/logs
    command: ["python", "-m", "uvicorn", "web_app:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/api/state >/dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

  frontend:
    build: ./frontend
    image: swarmagentic-frontend:latest
    depends_on:
      web:
        condition: service_healthy
    ports:
      - "3000:80"
    restart: unless-stopped

  desktop:
    build:
      context: ./SwarmAgentic-CSCI544
      dockerfile: docker/novnc/Dockerfile.novnc
    image: swarmagentic-desktop-novnc:latest
    ports:
      - "8080:8080"
    environment:
      - HF_HOME=/cache/huggingface
      - DISPLAY=:99
    volumes:
      - ./.cache/huggingface:/cache/huggingface
      - ./SwarmAgentic-CSCI544/results:/app/results
      - ./SwarmAgentic-CSCI544/logs:/app/logs
    restart: unless-stopped
